### ISSUE TITLE
eventing-natss cannot send messages after natss-streaming restarts 

### ISSUE THREAD

**Issue by wyyxd2017** [knative-sandbox/eventing-natss#190]
**Describe the bug**
I noticed that if natss-streaming restarts,
natss-ch-dispatcher can only receive messages, but cannot send messages to eventing. Is there any solution for this? 

 **Expected behavior**
I hope to still be able to send messages after natss-streaming restarts

**Comment by zhaojizhuang** [comment]
Hi, @wyyxd2017 can you show more log about `natss-ch-dispatcher`

**Comment by wyyxd2017** [comment]
When I deployed eventing-natss for the first time, the message can be sent to the url specified by subspcription through the connection of natss. If I restart natss-streaming, I can only receive messages from the broker, but cant't send messages to eventing. I judged that natss-stream has established a new connection, but it is still sent through the old natss-streaming connection

**Comment by wyyxd2017** [comment]
> Hi, @wyyxd2017 can you show more log about `natss-ch-dispatcher`, Or steps to produce the problem

When I deployed eventing-natss for the first time, the message can be sent to the url specified by subspcription through the connection of natss. If I restart natss-streaming, I can only receive messages from the broker, but not send messages. I judged that natss-stream has established a new connection, but it is still sent through the old natss-streaming connection

**Comment by zhaojizhuang** [comment]
can you show the result of `kubectl get broker,trigger,subscription,natschannel` and the log of `nats-ch-dispatcher` pod ?

**Comment by wyyxd2017** [comment]
> can you show the result of `kubectl get broker,trigger,subscription,natschannel` and the log of `nats-ch-dispatcher` pod ?

![image](https://user-images.githubusercontent.com/26351545/125589721-3331b6ca-7313-48ce-b64e-0f48b60e16ec.png)
![image](https://user-images.githubusercontent.com/26351545/125590407-a44e419a-5b70-4961-bdb1-273a82df1d2c.png)

**Comment by wyyxd2017** [comment]
> > can you show the result of `kubectl get broker,trigger,subscription,natschannel` and the log of `nats-ch-dispatcher` pod ?
> 
> ![image](https://user-images.githubusercontent.com/26351545/125589721-3331b6ca-7313-48ce-b64e-0f48b60e16ec.png)
> ![image](https://user-images.githubusercontent.com/26351545/125590407-a44e419a-5b70-4961-bdb1-273a82df1d2c.png)
The second picture is the log after restart

**Comment by zhaojizhuang** [comment]
`dispatcher` has received and publish events to the  nats-streaming, as seen in the log。
>  cannot send messages to eventing. 

And how do you find you can't send messages to eventing?  And what's the eventing-natss version?

**Comment by wyyxd2017** [comment]
> `dispatcher` has received and published events to the nats-streaming, as seen in the log。
> 
> > cannot send messages to eventing.
> 
> And how do you find you can't send messages to eventing? And what's the eventing-natss version?
![image](https://user-images.githubusercontent.com/26351545/125595918-7108586e-bc30-48ee-b290-7664f9d58b46.png)
![image](https://user-images.githubusercontent.com/26351545/125595475-f3869d34-30ff-4729-8208-c6776eafbfcc.png)
![image](https://user-images.githubusercontent.com/26351545/125595493-2d75cf21-fa83-4421-9bfd-313c456f4284.png)

These three log pictures are the date of natss-ch-dispatcher.
, The first one is a normal log, with receiving messages and sending messages;
The second picture is the log of the error report after restarting natss-streaming;
The third picture is the log after restart. You can see that there are received logs but no sent logs

**Comment by zhaojizhuang** [comment]
> The third picture is the log after restart. You can see that there are received logs but no sent logs

can you show the full yaml of `natsschannel` and `subscripton`, no sent logs means there is no subscriber when dispatch https://github.com/knative-sandbox/eventing-natss/blob/8b49c6b39b23d8526137c200322edb509015a8ca/pkg/dispatcher/dispatcher.go#L292

**Comment by wyyxd2017** [comment]
> > The third picture is the log after restart. You can see that there are received logs but no sent logs
> 
> can you show the full yaml of `natsschannel` and `subscripton`?, no sent logs means there is no subscriber when dispatch
> 
> https://github.com/knative-sandbox/eventing-natss/blob/8b49c6b39b23d8526137c200322edb509015a8ca/pkg/dispatcher/dispatcher.go#L292

**Comment by zhaojizhuang** [comment]
@wyyxd2017 still have the problem?

**Comment by wyyxd2017** [comment]
> @wyyxd2017 still have the problem?
Yes. Because ReconcileKind will only execute once for the NatssChannel resource, during this execution it will subscribe and generate a subscription. If natss-streaming reconnects, the previous subscribe is no longer valid.

**Comment by wyyxd2017** [comment]
@zhaojizhuang Yes. Because ReconcileKind will only execute once for the NatssChannel resource, during this execution it will subscribe and generate a subscription. If natss-streaming reconnects, the previous subscribe is no longer valid.
