### ISSUE TITLE
When will we support eventing-natss as an event source ? 

### ISSUE THREAD

**Issue by life-learner1** [knative-sandbox/eventing-natss#269]
**Problem**
Do you have any plans? 
related issue [here](https://github.com/knative-sandbox/eventing-natss/issues/93)

**Comment by zhaojizhuang** [comment]
yes, we will , we will support the `event-source` ,after the tasks completed cc @dan-j

**Comment by dan-j** [comment]
I'm all for supporting this via JetStream, but not so sure about NATS Streaming if the plan is to deprecate it soon.

**Comment by zhaojizhuang** [comment]
For NATS Streaming is deprected, So it's no need to support via NATS Streaming. In fact, we will deprecate natsschannel soon after JetStream completed
