### ISSUE TITLE
Duplication of events sent when NATS slow consumer error appears 

### ISSUE THREAD

**Issue by zadus** [knative-sandbox/eventing-natss#343]
**Describe the bug**
Currently I am using Jmeter to send varying loads direct to a Jetstream Server pod. The server accepts all messages quickly, and NATS Jetstream Dispatcher is subscribing to the stream and sending the messages to a simple Knative service that has a Trigger listening to all events and persisting in a postgreSQL database .

At low load, we are seeing fast persisting of messages in database. 
Bug only appears when we tried to send 25 000 messages to Jetstream server, and duplication of events is seen 
(prometheus logs shows 30+k messages sent by the Broker Filter pod)

Logs in Jetstream-ch-dispatcher shows:
ERROR MESSAGE: nats: slow consumer, messages dropped on connection [95700] for subscription on "_INBOX.vNtVZS4IIQ2XCN5w06S5uS"
![image](https://user-images.githubusercontent.com/30067975/174983956-511f4523-c344-4db6-9ca9-92f8c9b14708.png)

 **Expected behavior**
No duplication of messages to be observed, each message is only sent once from the Jetstream Dispatcher
 
**To Reproduce**
Running in a 4 Core, 16 GB RAM Ubuntu VM
Installed Knative serving with net-contour
Installed MT-channel broker
Used the yaml file included on knative site: https://github.com/knative-sandbox/eventing-natss/releases/download/knative-v1.4.0/eventing-natss.yaml

Increased the limits of the Jetstream server to use 1000m CPU and 500M Memory
Publishing to Jetstream server via NodePort

 **Knative release version**
1.4

 **Additional context**
Understood that a new version of Jetstream Dispatcher is in the works, but wondering if this issue will persist in future versions 

Please update if more information is needed on my end, thanks.

**Comment by chris93111** [comment]
Hi same issue, a slow consumer in sequence make a retry broker, a new events is generated and new message in stream nats and loop , is broken my knative events in one day
