### ISSUE TITLE
Make installable without "ko"

### ISSUE THREAD

**Issue by bbung** [knative-sandbox/eventing-natss#82]
**Problem**
I am not familiar with "ko" but it seems to be used to only resolve the image names. I cannot install without it as it produces errors with non-resolving imagenames.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
System Integrator

**Exit Criteria**
I can use kubectl apply -f *.. to install and it works without error messages. (May

**Time Estimate (optional):**
0

**Additional context (optional)**
Maybe i am wrong and everyone except me is using ko as a daily tool. But i think this should not be needed.

**Comment by vaikas** [comment]
Installing a Release, for example the latest 0.20:
https://github.com/knative-sandbox/eventing-natss/releases/tag/v0.20.0
Should not require ko. Does that work for you?

Installing head will require indeed ko.

**Comment by vaikas** [comment]
Oh, and if you want a non-release one, you can fetch a nightly here:
https://storage.googleapis.com/knative-nightly/eventing-natss/latest/eventing-natss.yaml

**Comment by bbung** [comment]
Hey, thanks. I may followed some misguiding links 🤔
