### ISSUE TITLE
Does eventing-natss support event source

### ISSUE THREAD

**Issue by yangyunfeng007** [knative-sandbox/eventing-natss#93]
Should we support event source in eventing-nats like other [event sources](https://knative.dev/docs/eventing/sources/
)?

**Comment by yangyunfeng007** [comment]
cc @zhaojizhuang

**Comment by n3wscott** [comment]
It is maybe not a good first issue, but yeah we should.

**Comment by yangyunfeng007** [comment]
@n3wscott When will we achieve this?

**Comment by DynamicRemo** [comment]
Hello everyone, any updates on the **NATS as a K-Native Event Source**?
I happen to found this example https://camel.apache.org/camel-kamelets/latest/nats-source.html based on KameletBinding (Camel-K, Apache Camel) and even after following everything with the setup, the KameletBinding always stays in the Error State.

Any leads or support would mean a lot. Cheers!
